const ApiError = require('../exceptions/api-error');


class DicktionaryController{


async addDictionary(req,res,next){
try {
  
} catch (error) {
  next(error)
}
}
async removeDictionary(req,res,next){
try {
  
} catch (error) {
  next(error)
}
}
async updateDictionary(req,res,next){
try {
  
} catch (error) {
  next(error)
}
}






}


module.exports= new DicktionaryController()